2019-12-07 16:36:07,320 ERROR: Exception on /post/4 [GET] [in /home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/honery/Documents/cursach/app/routes.py", line 181, in post
    post=post, answers=answers)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/honery/Documents/cursach/app/templates/post.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/honery/Documents/cursach/app/templates/post.html", line 17, in root
  File "/home/honery/Documents/cursach/app/templates/base.html", line 14, in root
    <span class="icon-bar"></span>
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/home/honery/Documents/cursach/app/templates/base.html", line 80, in block_content
  File "/home/honery/Documents/cursach/app/templates/post.html", line 38, in block_app_content
  File "/home/honery/Documents/cursach/app/templates/_post.html", line 13, in root
    <br>
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.Answer object' has no attribute 'author'
2019-12-07 16:41:27,179 INFO: Microblog startup [in /home/honery/Documents/cursach/app/__init__.py:33]
2019-12-07 16:41:34,344 ERROR: Exception on /post/5 [GET] [in /home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/honery/Documents/cursach/app/routes.py", line 181, in post
    post=post, answers=answers)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/honery/Documents/cursach/app/templates/post.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/honery/Documents/cursach/app/templates/post.html", line 17, in root
    </a>
  File "/home/honery/Documents/cursach/app/templates/base.html", line 14, in root
    <span class="icon-bar"></span>
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/home/honery/Documents/cursach/app/templates/base.html", line 80, in block_content
  File "/home/honery/Documents/cursach/app/templates/post.html", line 39, in block_app_content
  File "/home/honery/Documents/cursach/.env/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.Answer object' has no attribute 'author'
2019-12-07 16:41:59,418 INFO: Microblog startup [in /home/honery/Documents/cursach/app/__init__.py:33]
2019-12-07 16:45:43,344 INFO: Microblog startup [in /home/honery/Documents/cursach/app/__init__.py:33]
2019-12-07 16:45:51,962 INFO: Microblog startup [in /home/honery/Documents/cursach/app/__init__.py:33]
